services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8081:8080"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend